services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  
  mcp-server:
    build: ./mcp_server
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - backend
      - db
  
  course-sync:
    build: ./course-sync
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SYNC_INTERVAL=86400

  iep-quiz:
    build: ./iep-quiz
    ports:
      - "9001:9001"
    env_file:
      - ./iep-quiz/.env
    depends_on:
      - db
    environment:
      - PYTHONHTTPSVERIFY=0  # Temporarily disable certificate verification
      - UV_TIMEOUT=120       # Increase timeouts
      - UV_RETRIES=5         # Increase retry attempts
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  behavior-analyzer:
     build: ./behavior_analyzer
     restart: always
     ports:
       - "8001:8000"
     depends_on:
       - db
       - backend
     env_file:
       - .env

volumes:
  postgres_data:
    # Using default volume settings