services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    # Replace with your actual backend image/build info
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  iep-quiz:
    build: ./iep-quiz
    ports:
      - "9001:9001"
    env_file:
      - ./iep-quiz/.env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    # Using default volume settings