version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

    # mcp-server:
  #   build: 
  #     context: ./backend
  #     dockerfile: mcp.Dockerfile
  #   ports:
  #     - "8001:8001"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - db
  
  course-sync:
    build: ./course-sync
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SYNC_INTERVAL=86400

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres_data:
    # Using default volume settings
