[project]
name = "mcp-client"
version = "0.1.0"
description = "MCP Client for Planner AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[client]>=1.6.0",
    "openai>=1.76.0",
    "pydantic>=2.11.3",
    "python-dotenv>=1.0.0",
]
