from .ai_assistant import ChatRequest, ChatResponse
from .courses import get_courses, register_course, get_registered_courses, unregister_course
from .tasks import FixedObligationCreate, FixedObligationUpdate, CalendarEventCreate, CalendarEventUpdate, create_calendar_events_from_fixed, get_fixed_obligation, create_fixed_obligation, get_fixed_obligations, update_fixed_obligation, delete_fixed_obligation, FlexibleObligationCreate, FlexibleObligationUpdate, create_flexible_obligation, get_flexible_obligation, get_flexible_obligations, update_flexible_obligation, delete_flexible_obligation
from .tasks import get_academic_tasks, get_academic_tasks_by_course, AcademicTaskCreate, create_academic_task, get_calendar_events, get_calendar_event
from .user import get_user_info
from .auth import login