[project]
name = "iep-quiz"
version = "0.1.0"
description = "PDF→Images Ideas Extractor"
requires-python = ">=3.10"
dependencies = [
  "fastapi[standard]>=0.115.0",
  "uvicorn>=0.18.0",
  "pydantic>=2.7.1",
  "python-multipart>=0.0.9",
  "httpx>=0.27.0",
  "pdf2image>=1.16.0",
  "pillow>=10.0.0",
]