[project]
name = "iep-quiz"
version = "0.1.0"
description = "Quiz Generation IEP (FastAPI stub)"
requires-python = ">=3.10"
dependencies = [
  "fastapi[standard]>=0.115.0",
  "uvicorn>=0.18.0",
  "pdfplumber>=0.10.0",
  "python-multipart>=0.0.9",
  "httpx>=0.27.0",
]
